image: mcr.microsoft.com/dotnet/sdk:latest

variables:
  # 1) Name of directory where restore and build objects are stored.
  OBJECTS_DIRECTORY: 'devops/WebAppSwk'
  # 2) Name of directory used for keeping restored dependencies.
  NUGET_PACKAGES_DIRECTORY: 'devops/WebAppSwk/bin/Release/.nuget'
  # 3) A relative path to the source code from project repository root.
  # NOTE: Please edit this path so it matches the structure of your project!
  SOURCE_CODE_PATH: '*/devops/WebAppSwk'

stages:
  - build
build: 
  stage: build
  script: 
    - 'dotnet build /devops/WebAppSwk/WebAppSwk.csproj'